name: CI - Build and Compose Up

on:
  push:
    branches: [main, master,patch-1]
  pull_request:
    branches: [main, master,patch-1]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Build and run containers
        run: |
          docker-compose -f docker-compose.yml up --build -d
